name = "colby-recipe-backend"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1

[ai]
binding = "AI"

[browser]
binding = "BROWSER"

[[vectorize]]
binding = "VEC"
index_name = "recipes-index"

[[d1_databases]]
binding = "DB"
database_name = "DB"
database_id = "${D1_DATABASE_ID}"

[triggers]
crons = ["0 3 * * *"]
