name = "colby-recipe-backend"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

# HOST LOCAL FILES BINDING
[assets]
directory = "./public"
binding = "ASSETS"

# LOGS BINDING
[observability]
enabled = true
head_sampling_rate = 1

# WORKER AI BINDING
[ai]
binding = "AI"

# BROWSER RENDERING BINDING
[browser]
binding = "BROWSER"

# VECTORIZE BINDING
[[vectorize]]
binding = "VEC"
index_name = "recipes-index"

[[vectorize]]
binding = "APPLIANCE_VEC"
index_name = "appliance-manuals-index"

# D1 BINDING
[[d1_databases]]
binding = "DB"
database_name = "colby-recipe"
database_id = "a1e61fc6-cf5a-4900-9482-1089ce36f1d1"

# KV BINDING
[[kv_namespaces]]
binding = "KV"
id = "472e8adbec2f4aecac8d168a3910ca08"

# R2 BUCKET BINDING
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "menuforge-recipes"

[[r2_buckets]]
binding = "APPLIANCE_BUCKET"
bucket_name = "menuforge-appliances"

# CRON TRIGGERS
[triggers]
crons = ["0 3 * * *"]
